//! Artifacts System for generating and managing documentation, test results, and other outputs
//! Inspired by Google Antigravity's Artifact system

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

/// Artifact types that can be generated
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ArtifactType {
    /// Markdown documentation
    Documentation,
    /// Test results and coverage
    TestResults,
    /// Architecture diagrams
    Architecture,
    /// Performance reports
    Performance,
    /// Security audit reports
    SecurityAudit,
    /// Code review summaries
    CodeReview,
    /// Deployment guides
    Deployment,
    /// API documentation
    ApiDocs,
    /// Custom artifact type
    Custom(String),
}

impl ArtifactType {
    /// Get file extension for artifact type
    pub fn extension(&self) -> &str {
        match self {
            ArtifactType::Documentation => "md",
            ArtifactType::TestResults => "json",
            ArtifactType::Architecture => "md",
            ArtifactType::Performance => "md",
            ArtifactType::SecurityAudit => "md",
            ArtifactType::CodeReview => "md",
            ArtifactType::Deployment => "md",
            ArtifactType::ApiDocs => "md",
            ArtifactType::Custom(_) => "txt",
        }
    }

    /// Get icon for display
    pub fn icon(&self) -> &str {
        match self {
            ArtifactType::Documentation => "📝",
            ArtifactType::TestResults => "🧪",
            ArtifactType::Architecture => "🏗️",
            ArtifactType::Performance => "⚡",
            ArtifactType::SecurityAudit => "🔒",
            ArtifactType::CodeReview => "👀",
            ArtifactType::Deployment => "🚀",
            ArtifactType::ApiDocs => "📖",
            ArtifactType::Custom(_) => "📄",
        }
    }
}

/// An artifact generated by an agent or task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Artifact {
    /// Unique identifier
    pub id: String,
    /// Human-readable title
    pub title: String,
    /// Artifact type
    pub artifact_type: ArtifactType,
    /// Content (markdown, JSON, etc.)
    pub content: String,
    /// When the artifact was created
    pub created_at: SystemTime,
    /// When the artifact was last modified
    pub modified_at: SystemTime,
    /// Agent ID that created this artifact
    pub agent_id: Option<String>,
    /// Task ID that generated this artifact
    pub task_id: Option<uuid::Uuid>,
    /// Space ID this artifact belongs to
    pub space_id: Option<String>,
    /// Tags for organization
    pub tags: Vec<String>,
    /// Metadata (key-value pairs)
    pub metadata: HashMap<String, String>,
    /// Whether this artifact is pinned/starred
    pub pinned: bool,
    /// File path if artifact is saved to disk
    pub file_path: Option<PathBuf>,
}

impl Artifact {
    /// Create a new artifact
    pub fn new(title: String, artifact_type: ArtifactType, content: String) -> Self {
        let now = SystemTime::now();
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            title,
            artifact_type,
            content,
            created_at: now,
            modified_at: now,
            agent_id: None,
            task_id: None,
            space_id: None,
            tags: Vec::new(),
            metadata: HashMap::new(),
            pinned: false,
            file_path: None,
        }
    }

    /// Update artifact content
    pub fn update_content(&mut self, content: String) {
        self.content = content;
        self.modified_at = SystemTime::now();
    }

    /// Add tag
    pub fn add_tag(&mut self, tag: String) {
        if !self.tags.contains(&tag) {
            self.tags.push(tag);
        }
    }

    /// Remove tag
    pub fn remove_tag(&mut self, tag: &str) {
        self.tags.retain(|t| t != tag);
    }

    /// Set metadata
    pub fn set_metadata(&mut self, key: String, value: String) {
        self.metadata.insert(key, value);
    }

    /// Pin/unpin artifact
    pub fn toggle_pin(&mut self) {
        self.pinned = !self.pinned;
    }

    /// Save to disk
    pub fn save(
        &mut self,
        directory: &Path,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let filename = format!("{}.{}", self.id, self.artifact_type.extension());
        let path = directory.join(filename);
        std::fs::write(&path, &self.content)?;
        self.file_path = Some(path);
        self.modified_at = SystemTime::now();
        Ok(())
    }

    /// Load from disk
    pub fn load(path: &Path) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let content = std::fs::read_to_string(path)?;
        let filename = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown");
        let extension = path.extension().and_then(|s| s.to_str()).unwrap_or("");

        let artifact_type = match extension {
            "md" => ArtifactType::Documentation,
            "json" => ArtifactType::TestResults,
            _ => ArtifactType::Custom(extension.to_string()),
        };

        Ok(Self {
            id: filename.to_string(),
            title: filename.to_string(),
            artifact_type,
            content,
            created_at: SystemTime::now(),
            modified_at: SystemTime::now(),
            agent_id: None,
            task_id: None,
            space_id: None,
            tags: Vec::new(),
            metadata: HashMap::new(),
            pinned: false,
            file_path: Some(path.to_path_buf()),
        })
    }

    /// Get age
    pub fn age(&self) -> std::time::Duration {
        SystemTime::now()
            .duration_since(self.created_at)
            .unwrap_or_default()
    }
}

/// Manages artifacts collection
#[derive(Debug, Default)]
pub struct ArtifactManager {
    /// All artifacts indexed by ID
    artifacts: HashMap<String, Artifact>,
    /// Directory for saving artifacts
    storage_dir: Option<PathBuf>,
}

impl ArtifactManager {
    /// Create a new artifact manager
    pub fn new() -> Self {
        Self::default()
    }

    /// Set storage directory
    pub fn with_storage(mut self, dir: PathBuf) -> Self {
        self.storage_dir = Some(dir);
        self
    }

    /// Create a new artifact
    pub fn create_artifact(
        &mut self,
        title: String,
        artifact_type: ArtifactType,
        content: String,
    ) -> &Artifact {
        let artifact = Artifact::new(title, artifact_type, content);
        let id = artifact.id.clone();
        self.artifacts.insert(id.clone(), artifact);
        self.artifacts.get(&id).unwrap()
    }

    /// Get an artifact by ID
    pub fn get_artifact(&self, id: &str) -> Option<&Artifact> {
        self.artifacts.get(id)
    }

    /// Get a mutable reference to an artifact
    pub fn get_artifact_mut(&mut self, id: &str) -> Option<&mut Artifact> {
        self.artifacts.get_mut(id)
    }

    /// List all artifacts (optionally filtered)
    pub fn list_artifacts(&self, artifact_type: Option<&ArtifactType>) -> Vec<&Artifact> {
        self.artifacts
            .values()
            .filter(|a| {
                if let Some(t) = artifact_type {
                    a.artifact_type == *t
                } else {
                    true
                }
            })
            .collect()
    }

    /// Delete an artifact
    pub fn delete_artifact(&mut self, id: &str) -> bool {
        self.artifacts.remove(id).is_some()
    }

    /// Search artifacts
    pub fn search(&self, query: &str) -> Vec<&Artifact> {
        let query_lower = query.to_lowercase();
        self.artifacts
            .values()
            .filter(|a| {
                a.title.to_lowercase().contains(&query_lower)
                    || a.content.to_lowercase().contains(&query_lower)
                    || a.tags
                        .iter()
                        .any(|t| t.to_lowercase().contains(&query_lower))
            })
            .collect()
    }

    /// Get pinned artifacts
    pub fn pinned_artifacts(&self) -> Vec<&Artifact> {
        self.artifacts.values().filter(|a| a.pinned).collect()
    }

    /// Get artifacts by agent
    pub fn artifacts_by_agent(&self, agent_id: &str) -> Vec<&Artifact> {
        self.artifacts
            .values()
            .filter(|a| a.agent_id.as_deref() == Some(agent_id))
            .collect()
    }

    /// Get artifacts by space
    pub fn artifacts_by_space(&self, space_id: &str) -> Vec<&Artifact> {
        self.artifacts
            .values()
            .filter(|a| a.space_id.as_deref() == Some(space_id))
            .collect()
    }

    /// Get artifact count
    pub fn artifact_count(&self) -> usize {
        self.artifacts.len()
    }

    /// Save all artifacts to disk
    pub fn save_all(&mut self) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        if let Some(dir) = &self.storage_dir {
            std::fs::create_dir_all(dir)?;
            for artifact in self.artifacts.values_mut() {
                artifact.save(dir)?;
            }
        }
        Ok(())
    }

    /// Load all artifacts from disk
    pub fn load_all(&mut self) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        if let Some(dir) = &self.storage_dir {
            if dir.exists() {
                for entry in std::fs::read_dir(dir)? {
                    let entry = entry?;
                    let path = entry.path();
                    if path.is_file() {
                        if let Ok(artifact) = Artifact::load(&path) {
                            self.artifacts.insert(artifact.id.clone(), artifact);
                        }
                    }
                }
            }
        }
        Ok(())
    }

    /// Generate documentation from codebase
    pub fn generate_documentation(&mut self, title: String, content: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::Documentation, content)
    }

    /// Generate test results report
    pub fn generate_test_results(&mut self, title: String, results: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::TestResults, results)
    }

    /// Generate architecture diagram
    pub fn generate_architecture(&mut self, title: String, diagram: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::Architecture, diagram)
    }

    /// Generate performance report
    pub fn generate_performance_report(&mut self, title: String, report: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::Performance, report)
    }

    /// Generate security audit
    pub fn generate_security_audit(&mut self, title: String, audit: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::SecurityAudit, audit)
    }

    /// Generate code review summary
    pub fn generate_code_review(&mut self, title: String, review: String) -> &Artifact {
        self.create_artifact(title, ArtifactType::CodeReview, review)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_artifact_creation() {
        let artifact = Artifact::new(
            "Test Doc".to_string(),
            ArtifactType::Documentation,
            "# Test Content".to_string(),
        );
        assert_eq!(artifact.title, "Test Doc");
        assert_eq!(artifact.artifact_type, ArtifactType::Documentation);
        assert!(!artifact.pinned);
    }

    #[test]
    fn test_artifact_manager() {
        let mut manager = ArtifactManager::new();
        let artifact_id = {
            let artifact = manager.create_artifact(
                "Test".to_string(),
                ArtifactType::Documentation,
                "Content".to_string(),
            );
            artifact.id.clone()
        };
        assert_eq!(manager.artifact_count(), 1);
        assert!(manager.get_artifact(&artifact_id).is_some());
    }

    #[test]
    fn test_artifact_types() {
        assert_eq!(ArtifactType::Documentation.extension(), "md");
        assert_eq!(ArtifactType::TestResults.extension(), "json");
        assert_eq!(ArtifactType::Documentation.icon(), "📝");
    }
}
